### ISSUE TITLE
미이수 학기 선택 오류

### ISSUE THREAD

**Issue by mjh0528** [EntryDSM/poodle#157]
성적 입력란에서 미이수 학기를 선택하고 체크 해제하더라도 그대로 해당 학기 성적이 모두 X로 되어있습니다.

**Comment by sema0710** [comment]
미이수 학기 선택이 모두 X로 초기화 하는 로직입니다. 그런데 체크 해제했을 때 예전 값으로 돌리기엔, 이전 값을 기억하고 있기에 매우 애매해서 그렇게 처리하였습니다.

**Comment by sema0710** [comment]
로직 수정 예정입니다.

**Comment by woochanleee** [comment]
한번 상의해보겠습니다. 이슈 감사합니다!
